# Generated by Django 5.0.7 on 2024-07-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_remove_touristdestination_location_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdestination",
            name="state",
            field=models.CharField(
                choices=[("CA", "California"), ("NY", "New York"), ("TX", "Texas")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="weather",
            field=models.CharField(
                choices=[
                    ("Sunny", "Sunny"),
                    ("Cloudy", "Cloudy"),
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                ],
                max_length=100,
            ),
        ),
    ]
