# Generated by Django 5.0.7 on 2024-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0003_alter_touristdestination_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristdestination",
            old_name="district",
            new_name="location_district",
        ),
        migrations.RemoveField(
            model_name="touristdestination",
            name="state",
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="location_state",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="google_map_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="image",
            field=models.ImageField(upload_to="destination_images/"),
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="place_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="weather",
            field=models.CharField(max_length=100),
        ),
    ]
