# Generated by Django 5.0.7 on 2024-07-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "destinations",
            "0004_rename_district_touristdestination_location_district_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdestination",
            name="google_map_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="destination_images/"
            ),
        ),
    ]
